### ISSUE TITLE
Comment length too long!

### ISSUE THREAD

**Issue by danhunsaker** [danhunsaker/clover-reporter-action#2]
GitHub only supports comments up to 65534 bytes in length. We (and the upstream) need to figure out how to safely split (or simply truncate) reports that are longer.

**Comment by harnash** [comment]
@danhunsaker could we at least port change that will only process changed files?
```
filter-changed-files:
    description: Set to true to only comment with coverage on files changed in this commit
    required: false
    default: false
```
